FROM python:3.6

RUN pip3 install plumbum torch nose
RUN pip3 install nose numpy scipy flake8
RUN pip3 install fs tqdm scikit-image
RUN pip3 install allennlp
RUN pip3 install torchvision "wrapt<1.11.0"
RUN pip3 install attrs

# Pre-download weights files for resnet101
RUN python -c "from torchvision.models import resnet101; resnet101(True)"
WORKDIR /root
RUN mkdir Datasets
RUN wget -O Datasets/elmo_small_weights.hdf5 https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5
RUN wget -O Datasets/elmo_small_options.json https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_options.json
